modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="klv"
version="5.2"
displayName="Kailand"
credits="Refactorizado por Kailand"
displayURL="https://www.kailand.es/"
authors="Kailand"
description="Mod hecho para Kailand"

[[dependencies.klv]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




